/*******************************************************************************
 * Copyright (C) 2018 Elektrobit Automotive GmbH
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 ******************************************************************************/
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: target_agent_prot_template_plugin.proto

package com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions;

public final class TargetAgentTemplatePluginProtocol
{
    private TargetAgentTemplatePluginProtocol()
    {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry)
    {
    }

    public enum TemplatePluginMajorVersion implements com.google.protobuf.ProtocolMessageEnum {
        TEMPLATE_PLUGIN_MAJOR_VERSION(0, 0),;

        public static final int TEMPLATE_PLUGIN_MAJOR_VERSION_VALUE = 0;

        public final int getNumber()
        {
            return value;
        }

        public static TemplatePluginMajorVersion valueOf(int value)
        {
            switch (value)
            {
                case 0 :
                    return TEMPLATE_PLUGIN_MAJOR_VERSION;
                default :
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<TemplatePluginMajorVersion> internalGetValueMap()
        {
            return internalValueMap;
        }

        private static com.google.protobuf.Internal.EnumLiteMap<TemplatePluginMajorVersion> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<TemplatePluginMajorVersion>()
        {
            public TemplatePluginMajorVersion findValueByNumber(int number)
            {
                return TemplatePluginMajorVersion.valueOf( number );
            }
        };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor()
        {
            return getDescriptor().getValues().get( index );
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType()
        {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor()
        {
            return com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol
                    .getDescriptor().getEnumTypes().get( 0 );
        }

        private static final TemplatePluginMajorVersion[] VALUES = {TEMPLATE_PLUGIN_MAJOR_VERSION,};

        public static TemplatePluginMajorVersion valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc)
        {
            if (desc.getType() != getDescriptor())
            {
                throw new java.lang.IllegalArgumentException( "EnumValueDescriptor is not for this type." );
            }
            return VALUES[desc.getIndex()];
        }

        private final int index;
        private final int value;

        private TemplatePluginMajorVersion(int index, int value)
        {
            this.index = index;
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:TemplatePluginMajorVersion)
    }

    public enum TemplatePluginMinorVersion implements com.google.protobuf.ProtocolMessageEnum {
        TEMPLATE_PLUGIN_MINOR_VERSION(0, 1),;

        public static final int TEMPLATE_PLUGIN_MINOR_VERSION_VALUE = 1;

        public final int getNumber()
        {
            return value;
        }

        public static TemplatePluginMinorVersion valueOf(int value)
        {
            switch (value)
            {
                case 1 :
                    return TEMPLATE_PLUGIN_MINOR_VERSION;
                default :
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<TemplatePluginMinorVersion> internalGetValueMap()
        {
            return internalValueMap;
        }

        private static com.google.protobuf.Internal.EnumLiteMap<TemplatePluginMinorVersion> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<TemplatePluginMinorVersion>()
        {
            public TemplatePluginMinorVersion findValueByNumber(int number)
            {
                return TemplatePluginMinorVersion.valueOf( number );
            }
        };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor()
        {
            return getDescriptor().getValues().get( index );
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType()
        {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor()
        {
            return com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol
                    .getDescriptor().getEnumTypes().get( 1 );
        }

        private static final TemplatePluginMinorVersion[] VALUES = {TEMPLATE_PLUGIN_MINOR_VERSION,};

        public static TemplatePluginMinorVersion valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc)
        {
            if (desc.getType() != getDescriptor())
            {
                throw new java.lang.IllegalArgumentException( "EnumValueDescriptor is not for this type." );
            }
            return VALUES[desc.getIndex()];
        }

        private final int index;
        private final int value;

        private TemplatePluginMinorVersion(int index, int value)
        {
            this.index = index;
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:TemplatePluginMinorVersion)
    }

    public interface MessageDataOrBuilder extends com.google.protobuf.MessageOrBuilder
    {

        // required string message = 1;
        boolean hasMessage();

        String getMessage();
    }
    public static final class MessageData extends com.google.protobuf.GeneratedMessage implements MessageDataOrBuilder
    {
        // Use MessageData.newBuilder() to construct.
        private MessageData(Builder builder)
        {
            super( builder );
        }

        private MessageData(boolean noInit)
        {
        }

        private static final MessageData defaultInstance;

        public static MessageData getDefaultInstance()
        {
            return defaultInstance;
        }

        public MessageData getDefaultInstanceForType()
        {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor()
        {
            return com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.internal_static_MessageData_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable()
        {
            return com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.internal_static_MessageData_fieldAccessorTable;
        }

        private int bitField0_;
        // required string message = 1;
        public static final int MESSAGE_FIELD_NUMBER = 1;
        private java.lang.Object message_;

        public boolean hasMessage()
        {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public String getMessage()
        {
            java.lang.Object ref = message_;
            if (ref instanceof String)
            {
                return (String)ref;
            }
            else
            {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8( bs ))
                {
                    message_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getMessageBytes()
        {
            java.lang.Object ref = message_;
            if (ref instanceof String)
            {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8( (String)ref );
                message_ = b;
                return b;
            }
            else
            {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        private void initFields()
        {
            message_ = "";
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized()
        {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1)
                return isInitialized == 1;

            if (!hasMessage())
            {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException
        {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001))
            {
                output.writeBytes( 1, getMessageBytes() );
            }
            getUnknownFields().writeTo( output );
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize()
        {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001))
            {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize( 1, getMessageBytes() );
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException
        {
            return super.writeReplace();
        }

        public static com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData parseFrom(
                com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom( data ).buildParsed();
        }

        public static com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData parseFrom(
                com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom( data, extensionRegistry ).buildParsed();
        }

        public static com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData parseFrom(
                byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom( data ).buildParsed();
        }

        public static com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData parseFrom(
                byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom( data, extensionRegistry ).buildParsed();
        }

        public static com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData parseFrom(
                java.io.InputStream input) throws java.io.IOException
        {
            return newBuilder().mergeFrom( input ).buildParsed();
        }

        public static com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData parseFrom(
                java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return newBuilder().mergeFrom( input, extensionRegistry ).buildParsed();
        }

        public static com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData parseDelimitedFrom(
                java.io.InputStream input) throws java.io.IOException
        {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom( input ))
            {
                return builder.buildParsed();
            }
            else
            {
                return null;
            }
        }

        public static com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData parseDelimitedFrom(
                java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom( input, extensionRegistry ))
            {
                return builder.buildParsed();
            }
            else
            {
                return null;
            }
        }

        public static com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData parseFrom(
                com.google.protobuf.CodedInputStream input) throws java.io.IOException
        {
            return newBuilder().mergeFrom( input ).buildParsed();
        }

        public static com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData parseFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return newBuilder().mergeFrom( input, extensionRegistry ).buildParsed();
        }

        public static Builder newBuilder()
        {
            return Builder.create();
        }

        public Builder newBuilderForType()
        {
            return newBuilder();
        }

        public static Builder newBuilder(
                com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData prototype)
        {
            return newBuilder().mergeFrom( prototype );
        }

        public Builder toBuilder()
        {
            return newBuilder( this );
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent)
        {
            Builder builder = new Builder( parent );
            return builder;
        }

        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements
                    com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageDataOrBuilder
        {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor()
            {
                return com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.internal_static_MessageData_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable()
            {
                return com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.internal_static_MessageData_fieldAccessorTable;
            }

            // Construct using
            // com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData.newBuilder()
            private Builder()
            {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent)
            {
                super( parent );
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization()
            {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders)
                {
                }
            }

            private static Builder create()
            {
                return new Builder();
            }

            public Builder clear()
            {
                super.clear();
                message_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone()
            {
                return create().mergeFrom( buildPartial() );
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType()
            {
                return com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData
                        .getDescriptor();
            }

            public com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData getDefaultInstanceForType()
            {
                return com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData
                        .getDefaultInstance();
            }

            public com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData build()
            {
                com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData result = buildPartial();
                if (!result.isInitialized())
                {
                    throw newUninitializedMessageException( result );
                }
                return result;
            }

            private com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException
            {
                com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData result = buildPartial();
                if (!result.isInitialized())
                {
                    throw newUninitializedMessageException( result ).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData buildPartial()
            {
                com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData result = new com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData( this );
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001))
                {
                    to_bitField0_ |= 0x00000001;
                }
                result.message_ = message_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other)
            {
                if (other instanceof com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData)
                {
                    return mergeFrom( (com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData)other );
                }
                else
                {
                    super.mergeFrom( other );
                    return this;
                }
            }

            public Builder mergeFrom(
                    com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData other)
            {
                if (other == com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData
                        .getDefaultInstance())
                    return this;
                if (other.hasMessage())
                {
                    setMessage( other.getMessage() );
                }
                this.mergeUnknownFields( other.getUnknownFields() );
                return this;
            }

            public final boolean isInitialized()
            {
                if (!hasMessage())
                {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
            {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                        .newBuilder( this.getUnknownFields() );
                while (true)
                {
                    int tag = input.readTag();
                    switch (tag)
                    {
                        case 0 :
                            this.setUnknownFields( unknownFields.build() );
                            onChanged();
                            return this;
                        default : {
                            if (!parseUnknownField( input, unknownFields, extensionRegistry, tag ))
                            {
                                this.setUnknownFields( unknownFields.build() );
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10 : {
                            bitField0_ |= 0x00000001;
                            message_ = input.readBytes();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // required string message = 1;
            private java.lang.Object message_ = "";

            public boolean hasMessage()
            {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public String getMessage()
            {
                java.lang.Object ref = message_;
                if (!(ref instanceof String))
                {
                    String s = ((com.google.protobuf.ByteString)ref).toStringUtf8();
                    message_ = s;
                    return s;
                }
                else
                {
                    return (String)ref;
                }
            }

            public Builder setMessage(String value)
            {
                if (value == null)
                {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                message_ = value;
                onChanged();
                return this;
            }

            public Builder clearMessage()
            {
                bitField0_ = (bitField0_ & ~0x00000001);
                message_ = getDefaultInstance().getMessage();
                onChanged();
                return this;
            }

            void setMessage(com.google.protobuf.ByteString value)
            {
                bitField0_ |= 0x00000001;
                message_ = value;
                onChanged();
            }

            // @@protoc_insertion_point(builder_scope:MessageData)
        }

        static
        {
            defaultInstance = new MessageData( true );
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:MessageData)
    }

    private static com.google.protobuf.Descriptors.Descriptor internal_static_MessageData_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_MessageData_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor()
    {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static
    {
        java.lang.String[] descriptorData = {"\n\'target_agent_prot_template_plugin.prot"
                + "o\"\036\n\013MessageData\022\017\n\007message\030\001 \002(\t*?\n\032Tem"
                + "platePluginMajorVersion\022!\n\035TEMPLATE_PLUG"
                + "IN_MAJOR_VERSION\020\000*?\n\032TemplatePluginMino"
                + "rVersion\022!\n\035TEMPLATE_PLUGIN_MINOR_VERSIO" + "N\020\001Br\nMcom.elektrobit.ebrace.genivi.targ"
                + "etadapter.templateplugin.protocoldefinit" + "ionsB!TargetAgentTemplatePluginProtocol"};
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner()
        {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root)
            {
                descriptor = root;
                internal_static_MessageData_descriptor = getDescriptor().getMessageTypes().get( 0 );
                internal_static_MessageData_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable( internal_static_MessageData_descriptor,
                                                                                                                              new java.lang.String[]{
                                                                                                                                      "Message",},
                                                                                                                              com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData.class,
                                                                                                                              com.elektrobit.ebrace.genivi.targetadapter.templateplugin.protocoldefinitions.TargetAgentTemplatePluginProtocol.MessageData.Builder.class );
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom( descriptorData,
                                                                                       new com.google.protobuf.Descriptors.FileDescriptor[]{},
                                                                                       assigner );
    }

    // @@protoc_insertion_point(outer_class_scope)
}
