// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: target_agent_prot_log4j_plugin.proto

package com.elektrobit.ebrace.targetdata.adapter.log4j;

public final class Log4jTAProto {
  private Log4jTAProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LogDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string trace = 1;
    boolean hasTrace();
    String getTrace();
    
    // required string logLevel = 2;
    boolean hasLogLevel();
    String getLogLevel();
  }
  public static final class LogData extends
      com.google.protobuf.GeneratedMessage
      implements LogDataOrBuilder {
    // Use LogData.newBuilder() to construct.
    private LogData(Builder builder) {
      super(builder);
    }
    private LogData(boolean noInit) {}
    
    private static final LogData defaultInstance;
    public static LogData getDefaultInstance() {
      return defaultInstance;
    }
    
    public LogData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.internal_static_TargetAgent_Protocol_Log4j_LogData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.internal_static_TargetAgent_Protocol_Log4j_LogData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string trace = 1;
    public static final int TRACE_FIELD_NUMBER = 1;
    private java.lang.Object trace_;
    public boolean hasTrace() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getTrace() {
      java.lang.Object ref = trace_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          trace_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTraceBytes() {
      java.lang.Object ref = trace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        trace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string logLevel = 2;
    public static final int LOGLEVEL_FIELD_NUMBER = 2;
    private java.lang.Object logLevel_;
    public boolean hasLogLevel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getLogLevel() {
      java.lang.Object ref = logLevel_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          logLevel_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLogLevelBytes() {
      java.lang.Object ref = logLevel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        logLevel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      trace_ = "";
      logLevel_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTrace()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLogLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTraceBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLogLevelBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTraceBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLogLevelBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.internal_static_TargetAgent_Protocol_Log4j_LogData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.internal_static_TargetAgent_Protocol_Log4j_LogData_fieldAccessorTable;
      }
      
      // Construct using com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        trace_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        logLevel_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData.getDescriptor();
      }
      
      public com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData getDefaultInstanceForType() {
        return com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData.getDefaultInstance();
      }
      
      public com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData build() {
        com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData buildPartial() {
        com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData result = new com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.trace_ = trace_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.logLevel_ = logLevel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData) {
          return mergeFrom((com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData other) {
        if (other == com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData.getDefaultInstance()) return this;
        if (other.hasTrace()) {
          setTrace(other.getTrace());
        }
        if (other.hasLogLevel()) {
          setLogLevel(other.getLogLevel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTrace()) {
          
          return false;
        }
        if (!hasLogLevel()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              trace_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              logLevel_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string trace = 1;
      private java.lang.Object trace_ = "";
      public boolean hasTrace() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getTrace() {
        java.lang.Object ref = trace_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          trace_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTrace(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        trace_ = value;
        onChanged();
        return this;
      }
      public Builder clearTrace() {
        bitField0_ = (bitField0_ & ~0x00000001);
        trace_ = getDefaultInstance().getTrace();
        onChanged();
        return this;
      }
      void setTrace(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        trace_ = value;
        onChanged();
      }
      
      // required string logLevel = 2;
      private java.lang.Object logLevel_ = "";
      public boolean hasLogLevel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getLogLevel() {
        java.lang.Object ref = logLevel_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          logLevel_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLogLevel(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        logLevel_ = value;
        onChanged();
        return this;
      }
      public Builder clearLogLevel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        logLevel_ = getDefaultInstance().getLogLevel();
        onChanged();
        return this;
      }
      void setLogLevel(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        logLevel_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:TargetAgent.Protocol.Log4j.LogData)
    }
    
    static {
      defaultInstance = new LogData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:TargetAgent.Protocol.Log4j.LogData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TargetAgent_Protocol_Log4j_LogData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TargetAgent_Protocol_Log4j_LogData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$target_agent_prot_log4j_plugin.proto\022\032" +
      "TargetAgent.Protocol.Log4j\"*\n\007LogData\022\r\n" +
      "\005trace\030\001 \002(\t\022\020\n\010logLevel\030\002 \002(\tB>\n.com.el" +
      "ektrobit.ebrace.targetdata.adapter.log4j" +
      "B\014Log4jTAProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TargetAgent_Protocol_Log4j_LogData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TargetAgent_Protocol_Log4j_LogData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TargetAgent_Protocol_Log4j_LogData_descriptor,
              new java.lang.String[] { "Trace", "LogLevel", },
              com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData.class,
              com.elektrobit.ebrace.targetdata.adapter.log4j.Log4jTAProto.LogData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
