// Generated by delombok at Wed Aug 29 09:17:08 CEST 2018
/*******************************************************************************
 * Copyright (C) 2018 Elektrobit Automotive GmbH
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 ******************************************************************************/
package com.elektrobit.ebrace.core.datainput.api;

import com.elektrobit.ebrace.core.targetdata.api.json.JsonEventHandler;

import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
public class DataInput
{
    private String id;
    private DataStream stream;
    private DataStreamTokenizer tokenizer;
    private DataStreamParser parser;
    private boolean reading = false;

    public void startReading(JsonEventHandler jsonEventHandler)
    {
        reading = true;
        try
        {
            stream.open();
            tokenizer.setDataStream( stream );
            while (reading && tokenizer.hasNextMessage())
            {
                byte[] nextMessage = null;
                nextMessage = tokenizer.readNextMessage();
                String jsonResult = parser.parse( nextMessage );
                if (jsonEventHandler != null)
                {
                    jsonEventHandler.handle( jsonResult );
                }
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        finally
        {
            stopReading();
            try
            {
                stream.close();
            }
            catch (Exception e)
            {
                e.printStackTrace();
            }
        }
    }

    public void stopReading()
    {
        reading = false;
    }

}
