// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: target_agent_prot_singleton_gateway_plugin.proto

package com.elektrobit.ebrace.targetadapter.singletongateway.protobuf;

public final class SingletonGatewayTAProto {
  private SingletonGatewayTAProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public enum SgMessageType
      implements com.google.protobuf.Internal.EnumLite {
    MSG_TYPE_EVM(0, 0),
    MSG_TYPE_VIEW(1, 1),
    ;
    
    public static final int MSG_TYPE_EVM_VALUE = 0;
    public static final int MSG_TYPE_VIEW_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static SgMessageType valueOf(int value) {
      switch (value) {
        case 0: return MSG_TYPE_EVM;
        case 1: return MSG_TYPE_VIEW;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<SgMessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SgMessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SgMessageType>() {
            public SgMessageType findValueByNumber(int number) {
              return SgMessageType.valueOf(number);
            }
          };
    
    private final int value;
    
    private SgMessageType(int index, int value) {
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:TargetAgent.Protocol.SingletonGatewayPlugin.SgMessageType)
  }
  
  public interface SingletonGatewayMessageOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .TargetAgent.Protocol.SingletonGatewayPlugin.SgMessageType msgType = 1;
    boolean hasMsgType();
    com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SgMessageType getMsgType();
    
    // required string msgContent = 2;
    boolean hasMsgContent();
    String getMsgContent();
  }
  public static final class SingletonGatewayMessage extends
      com.google.protobuf.GeneratedMessageLite
      implements SingletonGatewayMessageOrBuilder {
    // Use SingletonGatewayMessage.newBuilder() to construct.
    private SingletonGatewayMessage(Builder builder) {
      super(builder);
    }
    private SingletonGatewayMessage(boolean noInit) {}
    
    private static final SingletonGatewayMessage defaultInstance;
    public static SingletonGatewayMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public SingletonGatewayMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required .TargetAgent.Protocol.SingletonGatewayPlugin.SgMessageType msgType = 1;
    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SgMessageType msgType_;
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SgMessageType getMsgType() {
      return msgType_;
    }
    
    // required string msgContent = 2;
    public static final int MSGCONTENT_FIELD_NUMBER = 2;
    private java.lang.Object msgContent_;
    public boolean hasMsgContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getMsgContent() {
      java.lang.Object ref = msgContent_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          msgContent_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMsgContentBytes() {
      java.lang.Object ref = msgContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        msgContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      msgType_ = com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SgMessageType.MSG_TYPE_EVM;
      msgContent_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMsgContentBytes());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMsgContentBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage, Builder>
        implements com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessageOrBuilder {
      // Construct using com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        msgType_ = com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SgMessageType.MSG_TYPE_EVM;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgContent_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage getDefaultInstanceForType() {
        return com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage.getDefaultInstance();
      }
      
      public com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage build() {
        com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage buildPartial() {
        com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage result = new com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgContent_ = msgContent_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage other) {
        if (other == com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SingletonGatewayMessage.getDefaultInstance()) return this;
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasMsgContent()) {
          setMsgContent(other.getMsgContent());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMsgType()) {
          
          return false;
        }
        if (!hasMsgContent()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SgMessageType value = com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SgMessageType.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                msgType_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msgContent_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .TargetAgent.Protocol.SingletonGatewayPlugin.SgMessageType msgType = 1;
      private com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SgMessageType msgType_ = com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SgMessageType.MSG_TYPE_EVM;
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SgMessageType getMsgType() {
        return msgType_;
      }
      public Builder setMsgType(com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SgMessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgType_ = value;
        
        return this;
      }
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = com.elektrobit.ebrace.targetadapter.singletongateway.protobuf.SingletonGatewayTAProto.SgMessageType.MSG_TYPE_EVM;
        
        return this;
      }
      
      // required string msgContent = 2;
      private java.lang.Object msgContent_ = "";
      public boolean hasMsgContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getMsgContent() {
        java.lang.Object ref = msgContent_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          msgContent_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMsgContent(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgContent_ = value;
        
        return this;
      }
      public Builder clearMsgContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgContent_ = getDefaultInstance().getMsgContent();
        
        return this;
      }
      void setMsgContent(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        msgContent_ = value;
        
      }
      
      // @@protoc_insertion_point(builder_scope:TargetAgent.Protocol.SingletonGatewayPlugin.SingletonGatewayMessage)
    }
    
    static {
      defaultInstance = new SingletonGatewayMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:TargetAgent.Protocol.SingletonGatewayPlugin.SingletonGatewayMessage)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
