// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: target_agent_prot_rmTest_plugin.proto

package com.elektrobit.ebrace.targetdata.adapter.rmtests;

public final class RmTestsProto {
  private RmTestsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum OperationType
      implements com.google.protobuf.ProtocolMessageEnum {
    RM_TESTS_CONSUME_CPU(0, 0),
    RM_TESTS_CONSUME_MEMORY(1, 1),
    RM_TESTS_LEAK_MEMORY(2, 2),
    ;
    
    public static final int RM_TESTS_CONSUME_CPU_VALUE = 0;
    public static final int RM_TESTS_CONSUME_MEMORY_VALUE = 1;
    public static final int RM_TESTS_LEAK_MEMORY_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static OperationType valueOf(int value) {
      switch (value) {
        case 0: return RM_TESTS_CONSUME_CPU;
        case 1: return RM_TESTS_CONSUME_MEMORY;
        case 2: return RM_TESTS_LEAK_MEMORY;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<OperationType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<OperationType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OperationType>() {
            public OperationType findValueByNumber(int number) {
              return OperationType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final OperationType[] VALUES = {
      RM_TESTS_CONSUME_CPU, RM_TESTS_CONSUME_MEMORY, RM_TESTS_LEAK_MEMORY, 
    };
    
    public static OperationType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private OperationType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:TargetAgent.Protocol.RmTests.OperationType)
  }
  
  public interface EntryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .TargetAgent.Protocol.RmTests.OperationType mKey = 1;
    boolean hasMKey();
    com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.OperationType getMKey();
    
    // optional uint32 mValue = 2;
    boolean hasMValue();
    int getMValue();
  }
  public static final class Entry extends
      com.google.protobuf.GeneratedMessage
      implements EntryOrBuilder {
    // Use Entry.newBuilder() to construct.
    private Entry(Builder builder) {
      super(builder);
    }
    private Entry(boolean noInit) {}
    
    private static final Entry defaultInstance;
    public static Entry getDefaultInstance() {
      return defaultInstance;
    }
    
    public Entry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.internal_static_TargetAgent_Protocol_RmTests_Entry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.internal_static_TargetAgent_Protocol_RmTests_Entry_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .TargetAgent.Protocol.RmTests.OperationType mKey = 1;
    public static final int MKEY_FIELD_NUMBER = 1;
    private com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.OperationType mKey_;
    public boolean hasMKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.OperationType getMKey() {
      return mKey_;
    }
    
    // optional uint32 mValue = 2;
    public static final int MVALUE_FIELD_NUMBER = 2;
    private int mValue_;
    public boolean hasMValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getMValue() {
      return mValue_;
    }
    
    private void initFields() {
      mKey_ = com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.OperationType.RM_TESTS_CONSUME_CPU;
      mValue_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, mKey_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, mValue_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, mKey_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, mValue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.EntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.internal_static_TargetAgent_Protocol_RmTests_Entry_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.internal_static_TargetAgent_Protocol_RmTests_Entry_fieldAccessorTable;
      }
      
      // Construct using com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        mKey_ = com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.OperationType.RM_TESTS_CONSUME_CPU;
        bitField0_ = (bitField0_ & ~0x00000001);
        mValue_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry.getDescriptor();
      }
      
      public com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry getDefaultInstanceForType() {
        return com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry.getDefaultInstance();
      }
      
      public com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry build() {
        com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry buildPartial() {
        com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry result = new com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mKey_ = mKey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mValue_ = mValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry) {
          return mergeFrom((com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry other) {
        if (other == com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry.getDefaultInstance()) return this;
        if (other.hasMKey()) {
          setMKey(other.getMKey());
        }
        if (other.hasMValue()) {
          setMValue(other.getMValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMKey()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.OperationType value = com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.OperationType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                mKey_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              mValue_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .TargetAgent.Protocol.RmTests.OperationType mKey = 1;
      private com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.OperationType mKey_ = com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.OperationType.RM_TESTS_CONSUME_CPU;
      public boolean hasMKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.OperationType getMKey() {
        return mKey_;
      }
      public Builder setMKey(com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.OperationType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        mKey_ = value;
        onChanged();
        return this;
      }
      public Builder clearMKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mKey_ = com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.OperationType.RM_TESTS_CONSUME_CPU;
        onChanged();
        return this;
      }
      
      // optional uint32 mValue = 2;
      private int mValue_ ;
      public boolean hasMValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getMValue() {
        return mValue_;
      }
      public Builder setMValue(int value) {
        bitField0_ |= 0x00000002;
        mValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearMValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mValue_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:TargetAgent.Protocol.RmTests.Entry)
    }
    
    static {
      defaultInstance = new Entry(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:TargetAgent.Protocol.RmTests.Entry)
  }
  
  public interface RmConfigurationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .TargetAgent.Protocol.RmTests.Entry configEntry = 1;
    java.util.List<com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry> 
        getConfigEntryList();
    com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry getConfigEntry(int index);
    int getConfigEntryCount();
    java.util.List<? extends com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.EntryOrBuilder> 
        getConfigEntryOrBuilderList();
    com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.EntryOrBuilder getConfigEntryOrBuilder(
        int index);
  }
  public static final class RmConfiguration extends
      com.google.protobuf.GeneratedMessage
      implements RmConfigurationOrBuilder {
    // Use RmConfiguration.newBuilder() to construct.
    private RmConfiguration(Builder builder) {
      super(builder);
    }
    private RmConfiguration(boolean noInit) {}
    
    private static final RmConfiguration defaultInstance;
    public static RmConfiguration getDefaultInstance() {
      return defaultInstance;
    }
    
    public RmConfiguration getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.internal_static_TargetAgent_Protocol_RmTests_RmConfiguration_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.internal_static_TargetAgent_Protocol_RmTests_RmConfiguration_fieldAccessorTable;
    }
    
    // repeated .TargetAgent.Protocol.RmTests.Entry configEntry = 1;
    public static final int CONFIGENTRY_FIELD_NUMBER = 1;
    private java.util.List<com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry> configEntry_;
    public java.util.List<com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry> getConfigEntryList() {
      return configEntry_;
    }
    public java.util.List<? extends com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.EntryOrBuilder> 
        getConfigEntryOrBuilderList() {
      return configEntry_;
    }
    public int getConfigEntryCount() {
      return configEntry_.size();
    }
    public com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry getConfigEntry(int index) {
      return configEntry_.get(index);
    }
    public com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.EntryOrBuilder getConfigEntryOrBuilder(
        int index) {
      return configEntry_.get(index);
    }
    
    private void initFields() {
      configEntry_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getConfigEntryCount(); i++) {
        if (!getConfigEntry(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < configEntry_.size(); i++) {
        output.writeMessage(1, configEntry_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < configEntry_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, configEntry_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfigurationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.internal_static_TargetAgent_Protocol_RmTests_RmConfiguration_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.internal_static_TargetAgent_Protocol_RmTests_RmConfiguration_fieldAccessorTable;
      }
      
      // Construct using com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getConfigEntryFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (configEntryBuilder_ == null) {
          configEntry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          configEntryBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration.getDescriptor();
      }
      
      public com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration getDefaultInstanceForType() {
        return com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration.getDefaultInstance();
      }
      
      public com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration build() {
        com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration buildPartial() {
        com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration result = new com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration(this);
        int from_bitField0_ = bitField0_;
        if (configEntryBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            configEntry_ = java.util.Collections.unmodifiableList(configEntry_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.configEntry_ = configEntry_;
        } else {
          result.configEntry_ = configEntryBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration) {
          return mergeFrom((com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration other) {
        if (other == com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration.getDefaultInstance()) return this;
        if (configEntryBuilder_ == null) {
          if (!other.configEntry_.isEmpty()) {
            if (configEntry_.isEmpty()) {
              configEntry_ = other.configEntry_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureConfigEntryIsMutable();
              configEntry_.addAll(other.configEntry_);
            }
            onChanged();
          }
        } else {
          if (!other.configEntry_.isEmpty()) {
            if (configEntryBuilder_.isEmpty()) {
              configEntryBuilder_.dispose();
              configEntryBuilder_ = null;
              configEntry_ = other.configEntry_;
              bitField0_ = (bitField0_ & ~0x00000001);
              configEntryBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getConfigEntryFieldBuilder() : null;
            } else {
              configEntryBuilder_.addAllMessages(other.configEntry_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getConfigEntryCount(); i++) {
          if (!getConfigEntry(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry.Builder subBuilder = com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addConfigEntry(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .TargetAgent.Protocol.RmTests.Entry configEntry = 1;
      private java.util.List<com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry> configEntry_ =
        java.util.Collections.emptyList();
      private void ensureConfigEntryIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          configEntry_ = new java.util.ArrayList<com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry>(configEntry_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry, com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry.Builder, com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.EntryOrBuilder> configEntryBuilder_;
      
      public java.util.List<com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry> getConfigEntryList() {
        if (configEntryBuilder_ == null) {
          return java.util.Collections.unmodifiableList(configEntry_);
        } else {
          return configEntryBuilder_.getMessageList();
        }
      }
      public int getConfigEntryCount() {
        if (configEntryBuilder_ == null) {
          return configEntry_.size();
        } else {
          return configEntryBuilder_.getCount();
        }
      }
      public com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry getConfigEntry(int index) {
        if (configEntryBuilder_ == null) {
          return configEntry_.get(index);
        } else {
          return configEntryBuilder_.getMessage(index);
        }
      }
      public Builder setConfigEntry(
          int index, com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry value) {
        if (configEntryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConfigEntryIsMutable();
          configEntry_.set(index, value);
          onChanged();
        } else {
          configEntryBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setConfigEntry(
          int index, com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry.Builder builderForValue) {
        if (configEntryBuilder_ == null) {
          ensureConfigEntryIsMutable();
          configEntry_.set(index, builderForValue.build());
          onChanged();
        } else {
          configEntryBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addConfigEntry(com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry value) {
        if (configEntryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConfigEntryIsMutable();
          configEntry_.add(value);
          onChanged();
        } else {
          configEntryBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addConfigEntry(
          int index, com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry value) {
        if (configEntryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConfigEntryIsMutable();
          configEntry_.add(index, value);
          onChanged();
        } else {
          configEntryBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addConfigEntry(
          com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry.Builder builderForValue) {
        if (configEntryBuilder_ == null) {
          ensureConfigEntryIsMutable();
          configEntry_.add(builderForValue.build());
          onChanged();
        } else {
          configEntryBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addConfigEntry(
          int index, com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry.Builder builderForValue) {
        if (configEntryBuilder_ == null) {
          ensureConfigEntryIsMutable();
          configEntry_.add(index, builderForValue.build());
          onChanged();
        } else {
          configEntryBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllConfigEntry(
          java.lang.Iterable<? extends com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry> values) {
        if (configEntryBuilder_ == null) {
          ensureConfigEntryIsMutable();
          super.addAll(values, configEntry_);
          onChanged();
        } else {
          configEntryBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearConfigEntry() {
        if (configEntryBuilder_ == null) {
          configEntry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          configEntryBuilder_.clear();
        }
        return this;
      }
      public Builder removeConfigEntry(int index) {
        if (configEntryBuilder_ == null) {
          ensureConfigEntryIsMutable();
          configEntry_.remove(index);
          onChanged();
        } else {
          configEntryBuilder_.remove(index);
        }
        return this;
      }
      public com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry.Builder getConfigEntryBuilder(
          int index) {
        return getConfigEntryFieldBuilder().getBuilder(index);
      }
      public com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.EntryOrBuilder getConfigEntryOrBuilder(
          int index) {
        if (configEntryBuilder_ == null) {
          return configEntry_.get(index);  } else {
          return configEntryBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.EntryOrBuilder> 
           getConfigEntryOrBuilderList() {
        if (configEntryBuilder_ != null) {
          return configEntryBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(configEntry_);
        }
      }
      public com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry.Builder addConfigEntryBuilder() {
        return getConfigEntryFieldBuilder().addBuilder(
            com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry.getDefaultInstance());
      }
      public com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry.Builder addConfigEntryBuilder(
          int index) {
        return getConfigEntryFieldBuilder().addBuilder(
            index, com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry.getDefaultInstance());
      }
      public java.util.List<com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry.Builder> 
           getConfigEntryBuilderList() {
        return getConfigEntryFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry, com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry.Builder, com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.EntryOrBuilder> 
          getConfigEntryFieldBuilder() {
        if (configEntryBuilder_ == null) {
          configEntryBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry, com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry.Builder, com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.EntryOrBuilder>(
                  configEntry_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          configEntry_ = null;
        }
        return configEntryBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:TargetAgent.Protocol.RmTests.RmConfiguration)
    }
    
    static {
      defaultInstance = new RmConfiguration(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:TargetAgent.Protocol.RmTests.RmConfiguration)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TargetAgent_Protocol_RmTests_Entry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TargetAgent_Protocol_RmTests_Entry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TargetAgent_Protocol_RmTests_RmConfiguration_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TargetAgent_Protocol_RmTests_RmConfiguration_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%target_agent_prot_rmTest_plugin.proto\022" +
      "\034TargetAgent.Protocol.RmTests\"R\n\005Entry\0229" +
      "\n\004mKey\030\001 \002(\0162+.TargetAgent.Protocol.RmTe" +
      "sts.OperationType\022\016\n\006mValue\030\002 \001(\r\"K\n\017RmC" +
      "onfiguration\0228\n\013configEntry\030\001 \003(\0132#.Targ" +
      "etAgent.Protocol.RmTests.Entry*`\n\rOperat" +
      "ionType\022\030\n\024RM_TESTS_CONSUME_CPU\020\000\022\033\n\027RM_" +
      "TESTS_CONSUME_MEMORY\020\001\022\030\n\024RM_TESTS_LEAK_" +
      "MEMORY\020\002B@\n0com.elektrobit.ebrace.target" +
      "data.adapter.rmtestsB\014RmTestsProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TargetAgent_Protocol_RmTests_Entry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TargetAgent_Protocol_RmTests_Entry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TargetAgent_Protocol_RmTests_Entry_descriptor,
              new java.lang.String[] { "MKey", "MValue", },
              com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry.class,
              com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.Entry.Builder.class);
          internal_static_TargetAgent_Protocol_RmTests_RmConfiguration_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_TargetAgent_Protocol_RmTests_RmConfiguration_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TargetAgent_Protocol_RmTests_RmConfiguration_descriptor,
              new java.lang.String[] { "ConfigEntry", },
              com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration.class,
              com.elektrobit.ebrace.targetdata.adapter.rmtests.RmTestsProto.RmConfiguration.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
