// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: target_agent_prot_simple_string_plugin.proto

package com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf;

public final class TargetAgentProtocolSimpleString {
  private TargetAgentProtocolSimpleString() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public enum SimpleStringPluginMajorVersion
      implements com.google.protobuf.Internal.EnumLite {
    SOCKET_READER_PLUGINMAJOR_VERSION(0, 0),
    ;
    
    public static final int SOCKET_READER_PLUGINMAJOR_VERSION_VALUE = 0;
    
    
    public final int getNumber() { return value; }
    
    public static SimpleStringPluginMajorVersion valueOf(int value) {
      switch (value) {
        case 0: return SOCKET_READER_PLUGINMAJOR_VERSION;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<SimpleStringPluginMajorVersion>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SimpleStringPluginMajorVersion>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SimpleStringPluginMajorVersion>() {
            public SimpleStringPluginMajorVersion findValueByNumber(int number) {
              return SimpleStringPluginMajorVersion.valueOf(number);
            }
          };
    
    private final int value;
    
    private SimpleStringPluginMajorVersion(int index, int value) {
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:TargetAgent.Protocol.SimpleStringPlugin.SimpleStringPluginMajorVersion)
  }
  
  public enum SimpleStringPluginMinorVersion
      implements com.google.protobuf.Internal.EnumLite {
    SOCKET_READER_PLUGINMINOR_VERSION(0, 1),
    ;
    
    public static final int SOCKET_READER_PLUGINMINOR_VERSION_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static SimpleStringPluginMinorVersion valueOf(int value) {
      switch (value) {
        case 1: return SOCKET_READER_PLUGINMINOR_VERSION;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<SimpleStringPluginMinorVersion>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SimpleStringPluginMinorVersion>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SimpleStringPluginMinorVersion>() {
            public SimpleStringPluginMinorVersion findValueByNumber(int number) {
              return SimpleStringPluginMinorVersion.valueOf(number);
            }
          };
    
    private final int value;
    
    private SimpleStringPluginMinorVersion(int index, int value) {
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:TargetAgent.Protocol.SimpleStringPlugin.SimpleStringPluginMinorVersion)
  }
  
  public interface SimpleStringMessageOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required string string_message = 1;
    boolean hasStringMessage();
    String getStringMessage();
  }
  public static final class SimpleStringMessage extends
      com.google.protobuf.GeneratedMessageLite
      implements SimpleStringMessageOrBuilder {
    // Use SimpleStringMessage.newBuilder() to construct.
    private SimpleStringMessage(Builder builder) {
      super(builder);
    }
    private SimpleStringMessage(boolean noInit) {}
    
    private static final SimpleStringMessage defaultInstance;
    public static SimpleStringMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public SimpleStringMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required string string_message = 1;
    public static final int STRING_MESSAGE_FIELD_NUMBER = 1;
    private java.lang.Object stringMessage_;
    public boolean hasStringMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getStringMessage() {
      java.lang.Object ref = stringMessage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          stringMessage_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStringMessageBytes() {
      java.lang.Object ref = stringMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        stringMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      stringMessage_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasStringMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStringMessageBytes());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStringMessageBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage, Builder>
        implements com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessageOrBuilder {
      // Construct using com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        stringMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage getDefaultInstanceForType() {
        return com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage.getDefaultInstance();
      }
      
      public com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage build() {
        com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage buildPartial() {
        com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage result = new com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stringMessage_ = stringMessage_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage other) {
        if (other == com.elektrobit.ebrace.genivi.targetadapter.simplestringplugin.protobuf.TargetAgentProtocolSimpleString.SimpleStringMessage.getDefaultInstance()) return this;
        if (other.hasStringMessage()) {
          setStringMessage(other.getStringMessage());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasStringMessage()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              stringMessage_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string string_message = 1;
      private java.lang.Object stringMessage_ = "";
      public boolean hasStringMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getStringMessage() {
        java.lang.Object ref = stringMessage_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          stringMessage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setStringMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stringMessage_ = value;
        
        return this;
      }
      public Builder clearStringMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stringMessage_ = getDefaultInstance().getStringMessage();
        
        return this;
      }
      void setStringMessage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        stringMessage_ = value;
        
      }
      
      // @@protoc_insertion_point(builder_scope:TargetAgent.Protocol.SimpleStringPlugin.SimpleStringMessage)
    }
    
    static {
      defaultInstance = new SimpleStringMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:TargetAgent.Protocol.SimpleStringPlugin.SimpleStringMessage)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
