////
Copyright (C) 2018 Elektrobit Automotive GmbH

This program and the accompanying materials are made
available under the terms of the Eclipse Public License 2.0
which is available at https://www.eclipse.org/legal/epl-2.0/

SPDX-License-Identifier: EPL-2.0
////
== High-level Architecture

{ebsolys} consists of the {targetagent}, collecting data on the target system machine and an Eclipse RCP based analysis tool-chain running on the host environment.

The {targetagent} is the gateway to the host and provides a plug-in framework that allows an easy integration of new data collectors if required.

The host application provides extendable means for data analysis. It is equipped with set of visualizations like charts, tables and a communication graph out of the box and can be extended through custom HTML visualizations.

<diagram>

== Data Model

The data model builds on events that will be assigned to a channel.

=== Events

Events contain a *time stamp* and a *value*. Time stamps have microsecond precision. Values can be _numeric_, _textual_ or _binary payload_. In case of a binary payload, decoders can be used to make it human readable.
Examples for an event would be

* the value of memory consumption of a process at a certain point in time.
* a developer trace message
* an inter-process communication message

=== Channels

Channels are groups of events.
Examples are

* CPU values of a process
* Trace messages on a tracing channel

=== Channel Groups

Channel groups can be used to group channels by a certain category.
Examples are

* CPU channels for all processes running on the monitored system
* Tracing channels for all tracing sources available on the monitored system.

== Data Processing

=== Views

Views are there to display data. Data in this context means payload of events. As this can be of a multitude of types, there are also different kinds of views available.

* *Line charts*, suitable for numeric data, configurable in scale, zoom level and appearance
* *Tables*, suitable for textual data, can be searched and filtered
* *Communication graph*, displaying communication data like inter-process or inter-processor communication, can be filtered
* *HTML views*, for flexible extension of viewing capabilities, can be used with any web-visualization framework

=== Time Markers

Time markers are used to correlate data across views. They can be created from the GUI or from a script and will have a timestamp and a name.

=== Decoders

Decoders are modules to make encoded event payloads human readable and better workable. {solys} includes decoders for D-Bus and PDML (network) data.

=== Scripting

All run-time data can be accessed from an integrated scripting module. Scripts can be written to perform different kinds of tasks. Automating an analysis, defining system level tests or taking metrics are just a few examples. The scripting language used is Xtend, which is a dialect of Java.
