// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: target_agent_prot_ctrl.proto

package com.elektrobit.ebrace.targetagent.protocol.ctrl;

public final class TargetAgentProtocolCtrl {
  private TargetAgentProtocolCtrl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum ProtHndlrCtrlMajorVersion
      implements com.google.protobuf.ProtocolMessageEnum {
    PROT_HNDLR_CTRL_MAJOR_VERSION(0, 1),
    ;
    
    public static final int PROT_HNDLR_CTRL_MAJOR_VERSION_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static ProtHndlrCtrlMajorVersion valueOf(int value) {
      switch (value) {
        case 1: return PROT_HNDLR_CTRL_MAJOR_VERSION;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ProtHndlrCtrlMajorVersion>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ProtHndlrCtrlMajorVersion>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtHndlrCtrlMajorVersion>() {
            public ProtHndlrCtrlMajorVersion findValueByNumber(int number) {
              return ProtHndlrCtrlMajorVersion.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final ProtHndlrCtrlMajorVersion[] VALUES = {
      PROT_HNDLR_CTRL_MAJOR_VERSION, 
    };
    
    public static ProtHndlrCtrlMajorVersion valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ProtHndlrCtrlMajorVersion(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:TargetAgent.Protocol.Ctrl.ProtHndlrCtrlMajorVersion)
  }
  
  public enum ProtHndlrCtrlMinorVersion
      implements com.google.protobuf.ProtocolMessageEnum {
    PROT_HNDLR_CTRL_MINOR_VERSION(0, 0),
    ;
    
    public static final int PROT_HNDLR_CTRL_MINOR_VERSION_VALUE = 0;
    
    
    public final int getNumber() { return value; }
    
    public static ProtHndlrCtrlMinorVersion valueOf(int value) {
      switch (value) {
        case 0: return PROT_HNDLR_CTRL_MINOR_VERSION;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ProtHndlrCtrlMinorVersion>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ProtHndlrCtrlMinorVersion>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtHndlrCtrlMinorVersion>() {
            public ProtHndlrCtrlMinorVersion findValueByNumber(int number) {
              return ProtHndlrCtrlMinorVersion.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final ProtHndlrCtrlMinorVersion[] VALUES = {
      PROT_HNDLR_CTRL_MINOR_VERSION, 
    };
    
    public static ProtHndlrCtrlMinorVersion valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ProtHndlrCtrlMinorVersion(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:TargetAgent.Protocol.Ctrl.ProtHndlrCtrlMinorVersion)
  }
  
  public enum ProtHndlrCtrlHeartbeatRequestTimeout
      implements com.google.protobuf.ProtocolMessageEnum {
    PROT_HNDLR_CTRL_HEARTBEAT_REQUEST_TIMEOUT(0, 3000),
    ;
    
    public static final int PROT_HNDLR_CTRL_HEARTBEAT_REQUEST_TIMEOUT_VALUE = 3000;
    
    
    public final int getNumber() { return value; }
    
    public static ProtHndlrCtrlHeartbeatRequestTimeout valueOf(int value) {
      switch (value) {
        case 3000: return PROT_HNDLR_CTRL_HEARTBEAT_REQUEST_TIMEOUT;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ProtHndlrCtrlHeartbeatRequestTimeout>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ProtHndlrCtrlHeartbeatRequestTimeout>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtHndlrCtrlHeartbeatRequestTimeout>() {
            public ProtHndlrCtrlHeartbeatRequestTimeout findValueByNumber(int number) {
              return ProtHndlrCtrlHeartbeatRequestTimeout.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.getDescriptor().getEnumTypes().get(2);
    }
    
    private static final ProtHndlrCtrlHeartbeatRequestTimeout[] VALUES = {
      PROT_HNDLR_CTRL_HEARTBEAT_REQUEST_TIMEOUT, 
    };
    
    public static ProtHndlrCtrlHeartbeatRequestTimeout valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ProtHndlrCtrlHeartbeatRequestTimeout(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:TargetAgent.Protocol.Ctrl.ProtHndlrCtrlHeartbeatRequestTimeout)
  }
  
  public enum ProtHndlrCtrlHeartbeatResponseTimeout
      implements com.google.protobuf.ProtocolMessageEnum {
    PROT_HNDLR_CTRL_HEARTBEAT_RESPONSE_TIMEOUT(0, 2000),
    ;
    
    public static final int PROT_HNDLR_CTRL_HEARTBEAT_RESPONSE_TIMEOUT_VALUE = 2000;
    
    
    public final int getNumber() { return value; }
    
    public static ProtHndlrCtrlHeartbeatResponseTimeout valueOf(int value) {
      switch (value) {
        case 2000: return PROT_HNDLR_CTRL_HEARTBEAT_RESPONSE_TIMEOUT;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ProtHndlrCtrlHeartbeatResponseTimeout>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ProtHndlrCtrlHeartbeatResponseTimeout>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtHndlrCtrlHeartbeatResponseTimeout>() {
            public ProtHndlrCtrlHeartbeatResponseTimeout findValueByNumber(int number) {
              return ProtHndlrCtrlHeartbeatResponseTimeout.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.getDescriptor().getEnumTypes().get(3);
    }
    
    private static final ProtHndlrCtrlHeartbeatResponseTimeout[] VALUES = {
      PROT_HNDLR_CTRL_HEARTBEAT_RESPONSE_TIMEOUT, 
    };
    
    public static ProtHndlrCtrlHeartbeatResponseTimeout valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ProtHndlrCtrlHeartbeatResponseTimeout(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:TargetAgent.Protocol.Ctrl.ProtHndlrCtrlHeartbeatResponseTimeout)
  }
  
  public enum ProtHandlerCtrlMessageId
      implements com.google.protobuf.ProtocolMessageEnum {
    PROT_HNDLR_CTRL_MESSAGE_INVALID(0, 0),
    PROT_HNDLR_CTRL_CMD_GET_VERSION_INFO_ID(1, 1),
    PROT_HNDLR_CTRL_CMD_TERMINATE_CONNECTION_ID(2, 2),
    PROT_HNDLR_CTRL_CMD_HEARTBEAT_REQUEST_MSG_ID(3, 3),
    PROT_HNDLR_CTRL_HEARTBEAT_MSG_ID(4, 10),
    PROT_HNDLR_CTRL_EVT_HEARTBEAT_RESPONSE_MSG_ID(5, 11),
    PROT_HNDLR_CTRL_EVT_VERSION_INFO_ID(6, 20),
    ;
    
    public static final int PROT_HNDLR_CTRL_MESSAGE_INVALID_VALUE = 0;
    public static final int PROT_HNDLR_CTRL_CMD_GET_VERSION_INFO_ID_VALUE = 1;
    public static final int PROT_HNDLR_CTRL_CMD_TERMINATE_CONNECTION_ID_VALUE = 2;
    public static final int PROT_HNDLR_CTRL_CMD_HEARTBEAT_REQUEST_MSG_ID_VALUE = 3;
    public static final int PROT_HNDLR_CTRL_HEARTBEAT_MSG_ID_VALUE = 10;
    public static final int PROT_HNDLR_CTRL_EVT_HEARTBEAT_RESPONSE_MSG_ID_VALUE = 11;
    public static final int PROT_HNDLR_CTRL_EVT_VERSION_INFO_ID_VALUE = 20;
    
    
    public final int getNumber() { return value; }
    
    public static ProtHandlerCtrlMessageId valueOf(int value) {
      switch (value) {
        case 0: return PROT_HNDLR_CTRL_MESSAGE_INVALID;
        case 1: return PROT_HNDLR_CTRL_CMD_GET_VERSION_INFO_ID;
        case 2: return PROT_HNDLR_CTRL_CMD_TERMINATE_CONNECTION_ID;
        case 3: return PROT_HNDLR_CTRL_CMD_HEARTBEAT_REQUEST_MSG_ID;
        case 10: return PROT_HNDLR_CTRL_HEARTBEAT_MSG_ID;
        case 11: return PROT_HNDLR_CTRL_EVT_HEARTBEAT_RESPONSE_MSG_ID;
        case 20: return PROT_HNDLR_CTRL_EVT_VERSION_INFO_ID;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ProtHandlerCtrlMessageId>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ProtHandlerCtrlMessageId>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtHandlerCtrlMessageId>() {
            public ProtHandlerCtrlMessageId findValueByNumber(int number) {
              return ProtHandlerCtrlMessageId.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.getDescriptor().getEnumTypes().get(4);
    }
    
    private static final ProtHandlerCtrlMessageId[] VALUES = {
      PROT_HNDLR_CTRL_MESSAGE_INVALID, PROT_HNDLR_CTRL_CMD_GET_VERSION_INFO_ID, PROT_HNDLR_CTRL_CMD_TERMINATE_CONNECTION_ID, PROT_HNDLR_CTRL_CMD_HEARTBEAT_REQUEST_MSG_ID, PROT_HNDLR_CTRL_HEARTBEAT_MSG_ID, PROT_HNDLR_CTRL_EVT_HEARTBEAT_RESPONSE_MSG_ID, PROT_HNDLR_CTRL_EVT_VERSION_INFO_ID, 
    };
    
    public static ProtHandlerCtrlMessageId valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ProtHandlerCtrlMessageId(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:TargetAgent.Protocol.Ctrl.ProtHandlerCtrlMessageId)
  }
  
  public interface ProtHandlerCtrlMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .TargetAgent.Protocol.Ctrl.ProtHandlerCtrlMessageId id = 1;
    boolean hasId();
    com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessageId getId();
    
    // optional .TargetAgent.Protocol.CommonDefinitions.Timestamp timestamp = 2;
    boolean hasTimestamp();
    com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp getTimestamp();
    com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.TimestampOrBuilder getTimestampOrBuilder();
    
    // optional .TargetAgent.Protocol.Ctrl.ProtHandlerCtrlEvtVersionInfo versionInfo = 20;
    boolean hasVersionInfo();
    com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo getVersionInfo();
    com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfoOrBuilder getVersionInfoOrBuilder();
  }
  public static final class ProtHandlerCtrlMessage extends
      com.google.protobuf.GeneratedMessage
      implements ProtHandlerCtrlMessageOrBuilder {
    // Use ProtHandlerCtrlMessage.newBuilder() to construct.
    private ProtHandlerCtrlMessage(Builder builder) {
      super(builder);
    }
    private ProtHandlerCtrlMessage(boolean noInit) {}
    
    private static final ProtHandlerCtrlMessage defaultInstance;
    public static ProtHandlerCtrlMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProtHandlerCtrlMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.internal_static_TargetAgent_Protocol_Ctrl_ProtHandlerCtrlMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.internal_static_TargetAgent_Protocol_Ctrl_ProtHandlerCtrlMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .TargetAgent.Protocol.Ctrl.ProtHandlerCtrlMessageId id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessageId id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessageId getId() {
      return id_;
    }
    
    // optional .TargetAgent.Protocol.CommonDefinitions.Timestamp timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp getTimestamp() {
      return timestamp_;
    }
    public com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.TimestampOrBuilder getTimestampOrBuilder() {
      return timestamp_;
    }
    
    // optional .TargetAgent.Protocol.Ctrl.ProtHandlerCtrlEvtVersionInfo versionInfo = 20;
    public static final int VERSIONINFO_FIELD_NUMBER = 20;
    private com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo versionInfo_;
    public boolean hasVersionInfo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo getVersionInfo() {
      return versionInfo_;
    }
    public com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfoOrBuilder getVersionInfoOrBuilder() {
      return versionInfo_;
    }
    
    private void initFields() {
      id_ = com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessageId.PROT_HNDLR_CTRL_MESSAGE_INVALID;
      timestamp_ = com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp.getDefaultInstance();
      versionInfo_ = com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasTimestamp()) {
        if (!getTimestamp().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasVersionInfo()) {
        if (!getVersionInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, id_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(20, versionInfo_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, id_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(20, versionInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.internal_static_TargetAgent_Protocol_Ctrl_ProtHandlerCtrlMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.internal_static_TargetAgent_Protocol_Ctrl_ProtHandlerCtrlMessage_fieldAccessorTable;
      }
      
      // Construct using com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTimestampFieldBuilder();
          getVersionInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessageId.PROT_HNDLR_CTRL_MESSAGE_INVALID;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (timestampBuilder_ == null) {
          timestamp_ = com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp.getDefaultInstance();
        } else {
          timestampBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (versionInfoBuilder_ == null) {
          versionInfo_ = com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo.getDefaultInstance();
        } else {
          versionInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage.getDescriptor();
      }
      
      public com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage getDefaultInstanceForType() {
        return com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage.getDefaultInstance();
      }
      
      public com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage build() {
        com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage buildPartial() {
        com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage result = new com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (timestampBuilder_ == null) {
          result.timestamp_ = timestamp_;
        } else {
          result.timestamp_ = timestampBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (versionInfoBuilder_ == null) {
          result.versionInfo_ = versionInfo_;
        } else {
          result.versionInfo_ = versionInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage) {
          return mergeFrom((com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage other) {
        if (other == com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        if (other.hasVersionInfo()) {
          mergeVersionInfo(other.getVersionInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (hasTimestamp()) {
          if (!getTimestamp().isInitialized()) {
            
            return false;
          }
        }
        if (hasVersionInfo()) {
          if (!getVersionInfo().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessageId value = com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessageId.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                id_ = value;
              }
              break;
            }
            case 18: {
              com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp.Builder subBuilder = com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp.newBuilder();
              if (hasTimestamp()) {
                subBuilder.mergeFrom(getTimestamp());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setTimestamp(subBuilder.buildPartial());
              break;
            }
            case 162: {
              com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo.Builder subBuilder = com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo.newBuilder();
              if (hasVersionInfo()) {
                subBuilder.mergeFrom(getVersionInfo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setVersionInfo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .TargetAgent.Protocol.Ctrl.ProtHandlerCtrlMessageId id = 1;
      private com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessageId id_ = com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessageId.PROT_HNDLR_CTRL_MESSAGE_INVALID;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessageId getId() {
        return id_;
      }
      public Builder setId(com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessageId value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessageId.PROT_HNDLR_CTRL_MESSAGE_INVALID;
        onChanged();
        return this;
      }
      
      // optional .TargetAgent.Protocol.CommonDefinitions.Timestamp timestamp = 2;
      private com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp timestamp_ = com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp, com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp.Builder, com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.TimestampOrBuilder> timestampBuilder_;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      public Builder setTimestamp(com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
          onChanged();
        } else {
          timestampBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setTimestamp(
          com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
          onChanged();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeTimestamp(com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              timestamp_ != com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp.getDefaultInstance()) {
            timestamp_ =
              com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
          } else {
            timestamp_ = value;
          }
          onChanged();
        } else {
          timestampBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearTimestamp() {
        if (timestampBuilder_ == null) {
          timestamp_ = com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp.getDefaultInstance();
          onChanged();
        } else {
          timestampBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp.Builder getTimestampBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      public com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp, com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp.Builder, com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.TimestampOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp, com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.Timestamp.Builder, com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.TimestampOrBuilder>(
                  timestamp_,
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }
      
      // optional .TargetAgent.Protocol.Ctrl.ProtHandlerCtrlEvtVersionInfo versionInfo = 20;
      private com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo versionInfo_ = com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo, com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo.Builder, com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfoOrBuilder> versionInfoBuilder_;
      public boolean hasVersionInfo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo getVersionInfo() {
        if (versionInfoBuilder_ == null) {
          return versionInfo_;
        } else {
          return versionInfoBuilder_.getMessage();
        }
      }
      public Builder setVersionInfo(com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo value) {
        if (versionInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          versionInfo_ = value;
          onChanged();
        } else {
          versionInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setVersionInfo(
          com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo.Builder builderForValue) {
        if (versionInfoBuilder_ == null) {
          versionInfo_ = builderForValue.build();
          onChanged();
        } else {
          versionInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeVersionInfo(com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo value) {
        if (versionInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              versionInfo_ != com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo.getDefaultInstance()) {
            versionInfo_ =
              com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo.newBuilder(versionInfo_).mergeFrom(value).buildPartial();
          } else {
            versionInfo_ = value;
          }
          onChanged();
        } else {
          versionInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearVersionInfo() {
        if (versionInfoBuilder_ == null) {
          versionInfo_ = com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo.getDefaultInstance();
          onChanged();
        } else {
          versionInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo.Builder getVersionInfoBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getVersionInfoFieldBuilder().getBuilder();
      }
      public com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfoOrBuilder getVersionInfoOrBuilder() {
        if (versionInfoBuilder_ != null) {
          return versionInfoBuilder_.getMessageOrBuilder();
        } else {
          return versionInfo_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo, com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo.Builder, com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfoOrBuilder> 
          getVersionInfoFieldBuilder() {
        if (versionInfoBuilder_ == null) {
          versionInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo, com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo.Builder, com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfoOrBuilder>(
                  versionInfo_,
                  getParentForChildren(),
                  isClean());
          versionInfo_ = null;
        }
        return versionInfoBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:TargetAgent.Protocol.Ctrl.ProtHandlerCtrlMessage)
    }
    
    static {
      defaultInstance = new ProtHandlerCtrlMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:TargetAgent.Protocol.Ctrl.ProtHandlerCtrlMessage)
  }
  
  public interface ProtHandlerCtrlEvtVersionInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 majorVersion = 1;
    boolean hasMajorVersion();
    int getMajorVersion();
    
    // required int32 minorVersion = 2;
    boolean hasMinorVersion();
    int getMinorVersion();
  }
  public static final class ProtHandlerCtrlEvtVersionInfo extends
      com.google.protobuf.GeneratedMessage
      implements ProtHandlerCtrlEvtVersionInfoOrBuilder {
    // Use ProtHandlerCtrlEvtVersionInfo.newBuilder() to construct.
    private ProtHandlerCtrlEvtVersionInfo(Builder builder) {
      super(builder);
    }
    private ProtHandlerCtrlEvtVersionInfo(boolean noInit) {}
    
    private static final ProtHandlerCtrlEvtVersionInfo defaultInstance;
    public static ProtHandlerCtrlEvtVersionInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProtHandlerCtrlEvtVersionInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.internal_static_TargetAgent_Protocol_Ctrl_ProtHandlerCtrlEvtVersionInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.internal_static_TargetAgent_Protocol_Ctrl_ProtHandlerCtrlEvtVersionInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 majorVersion = 1;
    public static final int MAJORVERSION_FIELD_NUMBER = 1;
    private int majorVersion_;
    public boolean hasMajorVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMajorVersion() {
      return majorVersion_;
    }
    
    // required int32 minorVersion = 2;
    public static final int MINORVERSION_FIELD_NUMBER = 2;
    private int minorVersion_;
    public boolean hasMinorVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getMinorVersion() {
      return minorVersion_;
    }
    
    private void initFields() {
      majorVersion_ = 0;
      minorVersion_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMajorVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMinorVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, majorVersion_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, minorVersion_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, majorVersion_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, minorVersion_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.internal_static_TargetAgent_Protocol_Ctrl_ProtHandlerCtrlEvtVersionInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.internal_static_TargetAgent_Protocol_Ctrl_ProtHandlerCtrlEvtVersionInfo_fieldAccessorTable;
      }
      
      // Construct using com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        majorVersion_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        minorVersion_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo.getDescriptor();
      }
      
      public com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo getDefaultInstanceForType() {
        return com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo.getDefaultInstance();
      }
      
      public com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo build() {
        com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo buildPartial() {
        com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo result = new com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.majorVersion_ = majorVersion_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.minorVersion_ = minorVersion_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo) {
          return mergeFrom((com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo other) {
        if (other == com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo.getDefaultInstance()) return this;
        if (other.hasMajorVersion()) {
          setMajorVersion(other.getMajorVersion());
        }
        if (other.hasMinorVersion()) {
          setMinorVersion(other.getMinorVersion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMajorVersion()) {
          
          return false;
        }
        if (!hasMinorVersion()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              majorVersion_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              minorVersion_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 majorVersion = 1;
      private int majorVersion_ ;
      public boolean hasMajorVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getMajorVersion() {
        return majorVersion_;
      }
      public Builder setMajorVersion(int value) {
        bitField0_ |= 0x00000001;
        majorVersion_ = value;
        onChanged();
        return this;
      }
      public Builder clearMajorVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        majorVersion_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 minorVersion = 2;
      private int minorVersion_ ;
      public boolean hasMinorVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getMinorVersion() {
        return minorVersion_;
      }
      public Builder setMinorVersion(int value) {
        bitField0_ |= 0x00000002;
        minorVersion_ = value;
        onChanged();
        return this;
      }
      public Builder clearMinorVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        minorVersion_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:TargetAgent.Protocol.Ctrl.ProtHandlerCtrlEvtVersionInfo)
    }
    
    static {
      defaultInstance = new ProtHandlerCtrlEvtVersionInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:TargetAgent.Protocol.Ctrl.ProtHandlerCtrlEvtVersionInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TargetAgent_Protocol_Ctrl_ProtHandlerCtrlMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TargetAgent_Protocol_Ctrl_ProtHandlerCtrlMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TargetAgent_Protocol_Ctrl_ProtHandlerCtrlEvtVersionInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TargetAgent_Protocol_Ctrl_ProtHandlerCtrlEvtVersionInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034target_agent_prot_ctrl.proto\022\031TargetAg" +
      "ent.Protocol.Ctrl\032*target_agent_prot_com" +
      "mon_definitions.proto\"\356\001\n\026ProtHandlerCtr" +
      "lMessage\022?\n\002id\030\001 \002(\01623.TargetAgent.Proto" +
      "col.Ctrl.ProtHandlerCtrlMessageId\022D\n\ttim" +
      "estamp\030\002 \001(\01321.TargetAgent.Protocol.Comm" +
      "onDefinitions.Timestamp\022M\n\013versionInfo\030\024" +
      " \001(\01328.TargetAgent.Protocol.Ctrl.ProtHan" +
      "dlerCtrlEvtVersionInfo\"K\n\035ProtHandlerCtr" +
      "lEvtVersionInfo\022\024\n\014majorVersion\030\001 \002(\005\022\024\n",
      "\014minorVersion\030\002 \002(\005*>\n\031ProtHndlrCtrlMajo" +
      "rVersion\022!\n\035PROT_HNDLR_CTRL_MAJOR_VERSIO" +
      "N\020\001*>\n\031ProtHndlrCtrlMinorVersion\022!\n\035PROT" +
      "_HNDLR_CTRL_MINOR_VERSION\020\000*V\n$ProtHndlr" +
      "CtrlHeartbeatRequestTimeout\022.\n)PROT_HNDL" +
      "R_CTRL_HEARTBEAT_REQUEST_TIMEOUT\020\270\027*X\n%P" +
      "rotHndlrCtrlHeartbeatResponseTimeout\022/\n*" +
      "PROT_HNDLR_CTRL_HEARTBEAT_RESPONSE_TIMEO" +
      "UT\020\320\017*\321\002\n\030ProtHandlerCtrlMessageId\022#\n\037PR" +
      "OT_HNDLR_CTRL_MESSAGE_INVALID\020\000\022+\n\'PROT_",
      "HNDLR_CTRL_CMD_GET_VERSION_INFO_ID\020\001\022/\n+" +
      "PROT_HNDLR_CTRL_CMD_TERMINATE_CONNECTION" +
      "_ID\020\002\0220\n,PROT_HNDLR_CTRL_CMD_HEARTBEAT_R" +
      "EQUEST_MSG_ID\020\003\022$\n PROT_HNDLR_CTRL_HEART" +
      "BEAT_MSG_ID\020\n\0221\n-PROT_HNDLR_CTRL_EVT_HEA" +
      "RTBEAT_RESPONSE_MSG_ID\020\013\022\'\n#PROT_HNDLR_C" +
      "TRL_EVT_VERSION_INFO_ID\020\024BJ\n/com.elektro" +
      "bit.ebrace.targetagent.protocol.ctrlB\027Ta" +
      "rgetAgentProtocolCtrl"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TargetAgent_Protocol_Ctrl_ProtHandlerCtrlMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TargetAgent_Protocol_Ctrl_ProtHandlerCtrlMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TargetAgent_Protocol_Ctrl_ProtHandlerCtrlMessage_descriptor,
              new java.lang.String[] { "Id", "Timestamp", "VersionInfo", },
              com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage.class,
              com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlMessage.Builder.class);
          internal_static_TargetAgent_Protocol_Ctrl_ProtHandlerCtrlEvtVersionInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_TargetAgent_Protocol_Ctrl_ProtHandlerCtrlEvtVersionInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TargetAgent_Protocol_Ctrl_ProtHandlerCtrlEvtVersionInfo_descriptor,
              new java.lang.String[] { "MajorVersion", "MinorVersion", },
              com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo.class,
              com.elektrobit.ebrace.targetagent.protocol.ctrl.TargetAgentProtocolCtrl.ProtHandlerCtrlEvtVersionInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.elektrobit.ebrace.targetagent.protocol.commondefinitions.TargetAgentProtocolCommonDefinitions.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
