// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: target_agent_prot_dbusCmdCtrl_plugin.proto

public final class TargetAgentProtDbusCmdCtrlPlugin {
  private TargetAgentProtDbusCmdCtrlPlugin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*target_agent_prot_dbusCmdCtrl_plugin.p" +
      "roto\032$target_agent_prot_dbus_monitor.pro" +
      "to"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.elektrobit.ebrace.protobuf.messagedefinitions.TargetAgentProtocolDBusTAProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
